{{- if .Values.core.env.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "firefly-iii.core.fullname" . }}
type: opaque
stringData:
  {{- range $key, $val := .Values.core.env.secret }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
{{- end}}
