{{- if .Values.importer.env.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "firefly-iii.importer.fullname" . }}
type: opaque
stringData:
  {{- range $key, $val := .Values.importer.env.secret }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
{{- end}}
