{{- if .Values.core.env.normal }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "firefly-iii.core.fullname" . }}
data:
  {{- range $key, $val := .Values.core.env.normal }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
{{- end }}
