{{- if .Values.database.enabled }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
  labels:
    {{- include "immich.database.labels" . | nindent 4 }}
  name: {{ include "immich.database.fullname" . }}
stringData:
  POSTGRES_PASSWORD: {{ .Values.database.password | quote }}
  {{- range $key, $val := .Values.database.env.secret }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
type: Opaque
{{- end }}