{{- if .Values.env.normal }}
apiVersion: v1
data:
  {{- range $key, $val := .Values.env.normal }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
kind: ConfigMap
metadata:
  labels:
    {{- include "ghost.labels" . | nindent 4 }}
  name: {{ include "ghost.fullname" . }}
{{- end }}
