{{- if .Values.env.secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ghost.fullname" . }}
  labels:
    {{- include "ghost.labels" . | nindent 4 }}
type: opaque
stringData:
  {{- range $key, $val := .Values.env.secret }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
{{- end -}}
