checks:
  addAllBuiltIn: true
  exclude:
    - "unset-cpu-requirements" # Ignored to avoid throttling https://spot.io/resources/kubernetes-architecture/kubernetes-cpu-limits-how-they-work-and-should-you-avoid-them/
    - "use-namespace"
    - "minimum-three-replicas"
    - "hpa-minimum-three-replicas"
    - "required-annotation-email"
    - "required-label-owner"
customChecks:
  - name: required-label-app
    template: required-label
    params:
      key: app
  - name: required-label-component
    template: required-label
    params:
      key: component
  - name: required-label-tier
    template: required-label
    params:
      key: tier
