checks:
  addAllBuiltIn: true
  exclude:
    - "unset-cpu-requirements"
    - "use-namespace"
    - "minimum-three-replicas"
    - "required-annotation-email"
    - "required-label-owner"
customChecks:
  - name: required-label-app
    template: required-label
    params:
      key: app
  - name: required-label-component
    template: required-label
    params:
      key: component
  - name: required-label-tier
    template: required-label
    params:
      key: tier
