{{- if .Values.nodejs.enable }}
{{- $nodejsFullname := printf "%s-nodejs" (include "vite.fullname" .) -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "vite.nodejs.labels" . | nindent 4 }}
  name: {{ $nodejsFullname }}
spec:
  ports:
    - name: http
      port: {{ .Values.nodejs.service.port }}
      protocol: TCP
      targetPort: http
  selector:
    {{- include "vite.nodejs.selectorLabels" . | nindent 4 }}
  type: {{ .Values.nodejs.service.type }}
{{- end }}
