{{- if .Values.redis.enable -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "drupal.redis.fullname" . }}
  labels:
    {{- include "drupal.redis.labels" . | nindent 4 }}
spec:
  {{- if not .Values.redis.autoscaling.enabled }}
  replicas: {{ .Values.redis.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "drupal.redis.matchLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.redis.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "drupal.redis.labels" . | nindent 8 }}
        {{- with .Values.redis.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.redis.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "drupal.redis.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.redis.podSecurityContext | nindent 8 }}
      containers:
        - name: redis
          securityContext:
            {{- toYaml .Values.redis.securityContext | nindent 12 }}
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.redis.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.redis.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.redis.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          volumeMounts:
            - name: redis-conf
              mountPath: /usr/local/etc/redis/redis.conf
              subPath: redis.conf
          args:
            - redis-server
            - /usr/local/etc/redis/redis.conf
      volumes:
        - name: drupal-json
          configMap:
            name: {{ include "drupal.redis.fullname" . }}
            items:
              - key: drupal.json
                path: drupal.json
        - name: drupal-ini
          configMap:
            name: {{ include "drupal.redis.fullname" . }}
            items:
              - key: drupal.ini
                path: drupal.ini
        {{- range $key, $volume := .Values.redis.volumes }}
        {{- if $volume.enabled }}
        - name: {{ $key }}
          {{- if eq $volume.type "persistentVolumeClaim" }}
          persistentVolumeClaim:
            claimName: {{ if $volume.existingClaim }}{{ $volume.existingClaim }}{{- else }}{{ $volume.claimName }}{{- end }}
          {{- else if eq $volume.type "emptyDir" }}
          emptyDir: { }
          {{- else if eq $volume.type "hostPath" }}
          hostPath:
            path: {{ $volume.hostPath }}
          {{- else }}
          {{ $volume.type }}: {{- toYaml $volume.config | nindent 16 }}
          {{- end }}
        {{- end }}
        {{- end }}
      {{- with .Values.redis.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
