{{- if .Values.env.normal }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wordpress.fullname" . }}
data:
  {{- range $key, $val := .Values.env.normal }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
  wordpress.ini: |-
{{ .Files.Get "config/php/wordpress.ini" | indent 4}}
{{- end }}
