{{- if not .Values.database.externalDatabase }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "firefly-iii.database.fullname" . }}
  labels:
    {{- include "firefly-iii.database.labels" . | nindent 4 }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "firefly-iii.database.selectorLabels" . | nindent 4 }}
{{- end}}
