apiVersion: v1
kind: Service
metadata:
  name: {{ include "firefly-iii.importer.fullname" . }}
  labels:
    {{- include "firefly-iii.importer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.importer.service.type }}
  ports:
    - port: {{ .Values.importer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "firefly-iii.importer.selectorLabels" . | nindent 4 }}
