{{- if .Values.env.normal }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nextjs.fullname" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
  labels:
      {{- include "nextjs.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.env.normal }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
{{- end}}
