{{- if .Values.cronjob.enabled }}
{{- $nextjsFullname := include "nextjs.fullname" . -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    ignore-check.kube-linter.io/env-value-from: "Secret is created by ExternalSecret operator at runtime"
    ignore-check.kube-linter.io/no-liveness-probe: "The cron job does not need liveness probe"
    ignore-check.kube-linter.io/no-readiness-probe: "The cron job does not need readiness probe"
  labels:
    {{- include "nextjs.labels" . | nindent 4 }}
  name: {{ include "nextjs.fullname" . }}-cronjob
spec:
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            ignore-check.kube-linter.io/env-value-from: "Secret is created by ExternalSecret operator at runtime"
            {{- with .Values.podAnnotations }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          labels:
            {{- include "nextjs.labels" . | nindent 12 }}
            {{- with .Values.podLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            -
              {{- if .Values.cronjob.args }}
              args:
                {{- toYaml .Values.cronjob.args | nindent 16 }}
              {{- end }}
              command:
                {{- toYaml .Values.cronjob.command | nindent 16 }}
              env:
                {{- if .Values.externalSecretsDbUrl.enabled }}
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      key: DATABASE_URL
                      name: {{ $nextjsFullname }}-db-eso
                {{- end }}
                {{- if and .Values.externalSecrets.enabled .Values.externalSecrets.awsProvider.enabled .Values.externalSecrets.data }}
                {{- range .Values.externalSecrets.data }}
                - name: {{ .envName | default .secretKey }}
                  valueFrom:
                    secretKeyRef:
                      key: {{ .secretKey }}
                      name: {{ $nextjsFullname }}-eso
                {{- end }}
                {{- end }}
                {{- range $key, $val := .Values.env.secret }}
                - name: {{ $key }}
                  valueFrom:
                    secretKeyRef:
                      key: {{ $key }}
                      name: {{ $nextjsFullname }}
                {{- end}}
                {{- range $key, $val := .Values.env.normal }}
                - name: {{ $key }}
                  valueFrom:
                    configMapKeyRef:
                      key: {{ $key }}
                      name: {{ $nextjsFullname }}
                {{- end}}
              image: "{{ .Values.cronjob.image.repository }}:{{ .Values.cronjob.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.cronjob.image.pullPolicy }}
              name: {{ .Chart.Name }}-cronjob
              {{- with .Values.cronjob.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.cronjob.securityContext }}
              securityContext:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              volumeMounts:
                {{- with .Values.volumeMounts }}
                  {{- toYaml . | nindent 16 }}
                {{- end }}
          dnsConfig:
            options:
              - name: ndots
                value: "2"
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: OnFailure
          {{- with .Values.podSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "nextjs.serviceAccountName" . }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumes:
            {{- with .Values.volumes }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
  schedule: {{ .Values.cronjob.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
{{- end }}
