apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nextjs.fullname" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
type: opaque
stringData:
  {{- range $key, $val := .Values.env.secret }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
