apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "drupal.drupal.fullname" . }}
data:
{{- if .Values.drupal.env.normal }}
  {{- range $key, $val := .Values.drupal.env.normal }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
{{- end }}
  drupal.ini: |
    {{ .Values.drupal.phpConfig | default (.Files.Get "config/drupal/drupal.ini") | nindent 4 }}
  drupal.json: |
    {{ .Values.drupal.unitConfig | default (.Files.Get "config/drupal/drupal.json") | nindent 4 }}
