{{- $fullName := include "firefly-iii.core.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "firefly-iii.core.labels" . | nindent 4 }}
spec:
  {{- if not .Values.core.autoscaling.enabled }}
  replicas: {{ .Values.core.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "firefly-iii.core.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.core.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "firefly-iii.core.labels" . | nindent 8 }}
        {{- with .Values.core.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.core.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.core.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.core.securityContext | nindent 12 }}
          image: "{{ .Values.core.image.repository }}:{{ .Values.core.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.core.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.core.service.port }}
              protocol: TCP
          env:
          {{- range $key, $val := .Values.core.env.secret }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: {{ $key }}
          {{- end}}
          {{- range $key, $val := .Values.core.env.normal }}
            - name: {{ $key }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: {{ $key }}
          {{- end}}
          livenessProbe:
            {{- toYaml .Values.core.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.core.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.core.resources | nindent 12 }}
          {{- with .Values.core.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.core.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.core.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.core.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.core.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
