{{- if not .Values.database.externalDatabase }}
{{- if .Values.database.env.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "firefly-iii.database.fullname" . }}
type: opaque
stringData:
  {{- range $key, $val := .Values.database.env.secret }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
{{- end}}
{{- end}}
