{{- if .Values.postgres.enable }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    ignore-check.kube-linter.io/no-read-only-root-fs: "PostgreSQL needs write access to data directory"
    reloader.stakater.com/auto: "true"
  labels:
    {{- include "outline.postgres.labels" . | nindent 4 }}
  name: {{ include "outline.postgres.fullname" . }}
spec:
  {{- if not .Values.postgres.autoscaling.enabled }}
  replicas: {{ .Values.postgres.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "outline.postgres.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "outline.postgres.fullname" . }}-headless
  template:
    metadata:
      {{- with .Values.postgres.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "outline.postgres.labels" . | nindent 8 }}
        {{- with .Values.postgres.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.postgres.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        -
          {{- if or .Values.postgres.env.normal .Values.postgres.env.secret }}
          env:
          {{- range $key, $val := .Values.postgres.env.secret }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  key: {{ $key }}
                  name: {{ include "outline.postgres.fullname" $ }}
          {{- end}}
          {{- range $key, $val := .Values.postgres.env.normal }}
            - name: {{ $key }}
              valueFrom:
                configMapKeyRef:
                  key: {{ $key }}
                  name: {{ include "outline.postgres.fullname" $ }}
          {{- end}}
          {{- end}}
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          {{- with .Values.postgres.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          name: postgres
          ports:
            - containerPort: {{ .Values.postgres.service.port }}
              name: postgres
              protocol: TCP
          {{- with .Values.postgres.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.postgres.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.postgres.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- if .Values.postgres.persistence.enabled }}
            - mountPath: {{ .Values.postgres.persistence.mountPath }}
              name: postgres-data
          {{- end }}
          {{- if .Values.database.ssl.enabled }}
            - mountPath: /etc/ssl/certs/database-ca.pem
              name: database-ca-cert
              readOnly: true
              subPath: database-ca.pem
          {{- end }}
          {{- with .Values.postgres.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      dnsConfig:
        options:
          - name: ndots
            value: "2"
      {{- with .Values.postgres.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.postgres.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      {{- with .Values.postgres.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "outline.postgres.serviceAccountName" . }}
      {{- if .Values.database.ssl.enabled }}
      volumes:
        - name: database-ca-cert
          secret:
            defaultMode: 0444
            secretName: {{ include "outline.fullname" . }}-database-ca
      {{- end }}
      {{- with .Values.postgres.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.postgres.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  updateStrategy:
    type: RollingUpdate
  {{- if .Values.postgres.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        labels:
          {{- include "outline.postgres.labels" . | nindent 10 }}
        name: postgres-data
      spec:
        accessModes:
          - {{ .Values.postgres.persistence.accessMode | quote }}
        resources:
          requests:
            storage: {{ .Values.postgres.persistence.size | quote }}
        {{- if .Values.postgres.persistence.storageClass }}
        {{- if (eq "-" .Values.postgres.persistence.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: {{ .Values.postgres.persistence.storageClass | quote }}
        {{- end }}
        {{- end }}
  {{- end }}
{{- end }}
