{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.awsProvider.enabled -}}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
  labels:
    {{- include "generic.labels" . | nindent 4 }}
  name: {{ include "generic.fullname" . }}
spec:
  provider:
    aws:
      auth:
        secretRef:
          accessKeyIDSecretRef:
            key: access-key
            name: {{ include "generic.fullname" . }}-awssm-iam
          secretAccessKeySecretRef:
            key: secret-access-key
            name: {{ include "generic.fullname" . }}-awssm-iam
      region: {{ .Values.externalSecrets.awsProvider.region }}
      service: SecretsManager
{{- end -}}
