{{- if .Values.env.normal }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "symfony.fullname" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
data:
  symfony.ini: |
    {{- range $key, $val := .Values.phpIni }}
    {{ $key }} = {{ $val | quote }}
    {{- end }}
  {{- range $key, $val := .Values.env.normal }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
{{- end}}
