{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "symfony.fullname" . }}
  labels:
    {{- include "symfony.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "symfony.name" . }}
      component: {{ .Values.component }}
  policyTypes:
    {{- toYaml .Values.networkPolicy.policyTypes | nindent 4 }}
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
{{- end }}
