{{- if and .Values.server.persistence.enabled (not .Values.server.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "immich.server.labels" . | nindent 4 }}
  name: {{ include "immich.server.fullname" . }}-uploads
spec:
  accessModes:
    - {{ .Values.server.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.server.persistence.size }}
  {{- if .Values.server.persistence.storageClass }}
  storageClassName: {{ .Values.server.persistence.storageClass }}
  {{- end }}
{{- end }}