apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "immich.server.labels" . | nindent 4 }}
  name: {{ include "immich.server.fullname" . }}
spec:
  ports:
    - name: http
      port: {{ .Values.server.service.port }}
      protocol: TCP
      targetPort: http
  selector:
    {{- include "immich.server.selectorLabels" . | nindent 4 }}
  type: {{ .Values.server.service.type }}