# Default values for wordpress.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

name: wordpress
tier: backend

image:
  repository: wordpress
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "6.5-apache"

env:
  normal:
    WORDPRESS_DB_HOST: ""
    WORDPRESS_DB_USER: ""
    WORDPRESS_DB_NAME: ""
  secret:
    WORDPRESS_DB_PASSWORD: ""

externalSecrets:
  enabled: false
  serviceAccountName: "external-secretes-deploy" # Used to rollout a new deployment after secret change
  awsRegion: eu-central-1
  secretsManagerSecretName: ""
  refreshInterval: 1m
  restartDeployCronSchedule: '0 2 * * SUN' # Every Sunday at 2AM
  awsAccess:
    access-key: ""
    secret-access-key: ""
  accessKeyIdSecret:
    name: wordpress-reddevs-awssm
    key: access-key
  secretAccessKeySecret:
    name: wordpress-reddevs-awssm
    key: secret-access-key

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  containerPort: 80

ingress:
  enabled: true
  className: ""
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/force-ssl-redirect: 'true'
    kubernetes.io/tls-acme: 'true'
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: wordpress-tls
      hosts:
        - chart-example.local

resources:
  requests:
    memory: 512Mi
  limits:
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

persistentVolume:
  claimName: "wordpress-files"
  storageClassName: "longhorn"
  existingClaim: ""
  size: 2Gi
  accessModes:
    - ReadWriteMany

nodeSelector: {}

tolerations: []

affinity: {}
