{{- if and .Values.machineLearning.enabled .Values.machineLearning.env.secret }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
  labels:
    {{- include "immich.machineLearning.labels" . | nindent 4 }}
  name: {{ include "immich.machineLearning.fullname" . }}
stringData:
  {{- range $key, $val := .Values.machineLearning.env.secret }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
type: Opaque
{{- end}}