{{- if and .Values.machineLearning.enabled .Values.machineLearning.serviceAccount.create -}}
apiVersion: v1
automountServiceAccountToken: {{ .Values.machineLearning.serviceAccount.automount }}
kind: ServiceAccount
metadata:
  {{- with .Values.machineLearning.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "immich.machineLearning.labels" . | nindent 4 }}
  name: {{ include "immich.machineLearning.serviceAccountName" . }}
{{- end }}