{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "wordpress.fullname" . }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ include "wordpress.fullname" . }}
    kind: SecretStore
  target:
    name: {{ include "wordpress.fullname" . }}
    creationPolicy: Merge
  data:
    - secretKey: WORDPRESS_DB_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.secretsManagerSecretName }}
        property: password
{{- end -}}
