{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "wordpress.fullname" . }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.externalSecrets.awsRegion }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: {{ .Values.externalSecrets.accessKeyIdSecret.name }}
            key: {{ .Values.externalSecrets.accessKeyIdSecret.key }}
          secretAccessKeySecretRef:
            name: {{ .Values.externalSecrets.secretAccessKeySecret.name }}
            key: {{ .Values.externalSecrets.secretAccessKeySecret.key }}
{{- end -}}
