{{- if .Values.imageCredentials.enabled }}
apiVersion: v1
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
kind: Secret
metadata:
  labels:
    {{- include "generic.labels" . | nindent 4 }}
  name: container-registry-cred
type: kubernetes.io/dockerconfigjson
{{- end }}
