{{- if and .Values.redis.enable .Values.redis.env.secret }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
  labels:
    {{- include "nextjs.redis.labels" . | nindent 4 }}
  name: {{ include "nextjs.redis.fullname" . }}
stringData:
  {{- range $key, $val := .Values.redis.env.secret }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
type: Opaque
{{- end }}
