{{- if .Values.storybook.enable -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nextjs.storybook.fullname" . }}
  labels:
    {{- include "nextjs.storybook.labels" . | nindent 4 }}
spec:
  {{- if not .Values.storybook.autoscaling.enabled }}
  replicas: {{ .Values.storybook.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nextjs.storybook.matchLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.storybook.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nextjs.storybook.labels" . | nindent 8 }}
        {{- with .Values.storybook.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.storybook.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nextjs.storybook.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.storybook.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.storybook.securityContext | nindent 12 }}
          image: "{{ .Values.storybook.image.repository }}:{{ .Values.storybook.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.storybook.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.storybook.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.storybook.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.storybook.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.storybook.resources | nindent 12 }}
          {{- with .Values.storybook.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.storybook.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.storybook.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.storybook.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.storybook.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
