{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.awsProvider.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nextjs.fullname" . }}-awssm-iam
  labels:
    {{- include "nextjs.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
type: opaque
stringData:
  access-key: {{ .Values.externalSecrets.awsProvider.iam.accessKey | quote }}
  secret-access-key: {{ .Values.externalSecrets.awsProvider.iam.secretAccessKey | quote }}
{{- end -}}
