{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.awsProvider.enabled -}}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "nextjs.fullname" . }}
  labels:
    {{- include "nextjs.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.externalSecrets.awsProvider.region }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: {{ include "nextjs.fullname" . }}-awssm-iam
            key: access-key
          secretAccessKeySecretRef:
            name: {{ include "nextjs.fullname" . }}-awssm-iam
            key: secret-access-key
{{- end -}}
