{{- if and .Values.externalSecretsDbUrl.enabled .Values.externalSecretsDbUrl.awsProvider.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nextjs.fullname" . }}-awssm-db-iam
  labels:
    {{- include "nextjs.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
type: opaque
stringData:
  access-key: {{ .Values.externalSecretsDbUrl.awsProvider.iam.accessKey | quote }}
  secret-access-key: {{ .Values.externalSecretsDbUrl.awsProvider.iam.secretAccessKey | quote }}
{{- end -}}
