{{- if and .Values.externalSecretsDbUrl.enabled .Values.externalSecretsDbUrl.awsProvider.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "nextjs.fullname" . }}-db
  labels:
    {{- include "nextjs.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
spec:
  refreshInterval: {{ .Values.externalSecretsDbUrl.refreshInterval }}
  secretStoreRef:
    name: {{ include "nextjs.fullname" . }}
    kind: SecretStore
  target:
    name: {{ include "nextjs.fullname" . }}-db-eso
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.externalSecretsDbUrl.rdsSecretKey }}
  # Build a single DATABASE_URL string out of the fields in .data
  template:
    type: Opaque
    stringData:
      DATABASE_URL: >-
        {{ printf "%s://%s:%s@%s:%s/%s"
          .Values.externalSecretsDbUrl.data.engine
          (index .data "username")
          (index .data "password")
          .Values.externalSecretsDbUrl.data.host
          .Values.externalSecretsDbUrl.data.port
          .Values.externalSecretsDbUrl.data.dbName
        }}
{{- end }}
