{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.awsProvider.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
  name: {{ include "wordpress.fullname" . }}
spec:
  data:
    {{- range .Values.externalSecrets.data }}
    - remoteRef:
        key: {{ .remoteRef.key }}
        {{- if .remoteRef.property }}
        property: {{ .remoteRef.property }}
        {{- end }}
        {{- if .remoteRef.version }}
        version: {{ .remoteRef.version }}
        {{- end }}
      secretKey: {{ .secretKey }}
    {{- end }}
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: SecretStore
    name: {{ include "wordpress.fullname" . }}
  target:
    creationPolicy: Owner
    name: {{ include "wordpress.fullname" . }}-eso
{{- end -}}
