{{- if .Values.env.secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.fullname" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
type: opaque
stringData:
  {{- range $key, $val := .Values.env.secret }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
{{- end -}}
