apiVersion: v1
kind: Service
metadata:
  name: {{ include "drupal.drupal.fullname" . }}
  labels:
    {{- include "drupal.drupal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.drupal.service.type }}
  ports:
    - port: {{ .Values.drupal.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "drupal.drupal.matchLabels" . | nindent 4 }}
