{{- if and .Values.redis.enable .Values.redis.env.normal }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "outline.redis.fullname" . }}
  labels:
    {{- include "outline.redis.labels" . | nindent 4 }}
data:
{{- range $key, $val := .Values.redis.env.normal }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
{{- end }}
