{{- if and .Values.redis.enable .Values.redis.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "outline.redis.fullname" . }}
  labels:
    {{- include "outline.redis.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "outline.redis.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- with .Values.redis.networkPolicy.policyTypes }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.redis.networkPolicy.ingress }}
  ingress:
    {{- with .Values.redis.networkPolicy.ingress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
