{{- if .Values.redis.enable }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "outline.redis.labels" . | nindent 4 }}
  name: {{ include "outline.redis.fullname" . }}
spec:
  ports:
    - name: redis
      port: {{ .Values.redis.service.port }}
      protocol: TCP
      targetPort: redis
  selector:
    {{- include "outline.redis.selectorLabels" . | nindent 4 }}
  type: {{ .Values.redis.service.type }}
{{- end }}
