{{- if .Values.importer.env.normal }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "firefly-iii.importer.fullname" . }}
data:
  {{- range $key, $val := .Values.importer.env.normal }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
{{- end }}
