{{- if .Values.drupal.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "drupal.drupal.serviceAccountName" . }}
  labels:
    {{- include "drupal.drupal.labels" . | nindent 4 }}
  {{- with .Values.drupal.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.drupal.serviceAccount.automount }}
{{- end }}
