{{- if and .Values.redis.enable .Values.redis.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ghost.redis.fullname" . }}
  labels:
    {{- include "ghost.redis.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "ghost.name" . }}
      component: {{ .Values.redis.component }}
  policyTypes:
    {{- toYaml .Values.redis.networkPolicy.policyTypes | nindent 4 }}
  ingress:
    {{- toYaml .Values.redis.networkPolicy.ingress | nindent 4 }}
{{- end }}
