{{- if and .Values.redis.enable .Values.redis.env.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ghost.redis.fullname" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
  labels:
      {{- include "ghost.redis.labels" . | nindent 4 }}
type: opaque
stringData:
  {{- range $key, $val := .Values.redis.env.secret }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
{{- end}}
