{{- if and .Values.redis.enable .Values.redis.env.secret (not .Values.redis.env.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "ghost.redis.labels" . | nindent 4 }}
  name: {{ include "ghost.redis.fullname" . }}
stringData:
  {{- range $key, $val := .Values.redis.env.secret }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
type: Opaque
{{- end}}
