{{- if and .Values.externalSecretsDbUrl.enabled .Values.externalSecretsDbUrl.awsProvider.enabled -}}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
  labels:
    {{- include "symfony.labels" . | nindent 4 }}
  name: {{ include "symfony.fullname" . }}-db
spec:
  provider:
    aws:
      auth:
        secretRef:
          accessKeyIDSecretRef:
            key: access-key
            name: {{ include "symfony.fullname" . }}-awssm-db-iam
          secretAccessKeySecretRef:
            key: secret-access-key
            name: {{ include "symfony.fullname" . }}-awssm-db-iam
      region: {{ .Values.externalSecrets.awsProvider.region }}
      service: SecretsManager
{{- end -}}
