{{- if and .Values.externalSecretsDbUrl.enabled .Values.externalSecretsDbUrl.awsProvider.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
  labels:
    {{- include "symfony.labels" . | nindent 4 }}
  name: {{ include "symfony.fullname" . }}-db
spec:
  data:
    -
      remoteRef:
        key: {{ .Values.externalSecretsDbUrl.rdsSecretKey }}
        property: username
      secretKey: username
    -
      remoteRef:
        key: {{ .Values.externalSecretsDbUrl.rdsSecretKey }}
        property: password
      secretKey: password
  refreshInterval: {{ .Values.externalSecretsDbUrl.refreshInterval }}
  secretStoreRef:
    kind: SecretStore
    name: {{ include "symfony.fullname" . }}-db
  target:
    creationPolicy: Owner
    name: {{ include "symfony.fullname" . }}-db-eso
    template:
      data:
        DATABASE_URL: |
          {{`{{- $engine := `}}"{{ .Values.externalSecretsDbUrl.data.engine }}"{{` -}}
          {{- $host := `}}"{{ .Values.externalSecretsDbUrl.data.host }}"{{` -}}
          {{- $port := `}}"{{ .Values.externalSecretsDbUrl.data.port }}"{{` -}}
          {{- $dbname := `}}"{{ .Values.externalSecretsDbUrl.data.dbName }}"{{` -}}
          {{- $username := .username | urlquery -}}
          {{- $password := .password | urlquery -}}
          {{ $engine }}://{{ $username }}:{{ $password }}@{{ $host }}:{{ $port }}/{{ $dbname }}`}}
      engineVersion: v2
      type: Opaque
{{- end }}
