{{- if .Values.env.secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "symfony.fullname" . }}
  labels:
    {{- include "symfony.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
type: opaque
stringData:
  {{- range $key, $val := .Values.env.secret }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
{{- end -}}
