{{- if .Values.env.normal }}
apiVersion: v1
data:
{{- range $key, $val := .Values.env.normal }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
kind: ConfigMap
metadata:
  labels:
    {{- include "outline.labels" . | nindent 4 }}
  name: {{ include "outline.fullname" . }}
{{- end }}
