apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "outline.labels" . | nindent 4 }}
  name: {{ include "outline.fullname" . }}
spec:
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: http
  selector:
    {{- include "outline.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
