{{- if or .Values.env.normal .Values.phpIni .Values.nginxUnit.enable }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "symfony.fullname" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
  labels:
    {{- include "symfony.labels" . | nindent 4 }}
data:
  {{- if .Values.phpIni }}
  symfony.ini: |
    {{- range $key, $val := .Values.phpIni }}
    {{ $key }} = {{ $val | quote }}
    {{- end }}
  {{- end }}
  {{- if .Values.nginxUnit.enable }}
  symfony.json: |
    {{- .Values.nginxUnit.content | nindent 4 }}
  {{- end }}
  {{- range $key, $val := .Values.env.normal }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
{{- end}}
