apiVersion: v1
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
kind: Secret
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
  labels:
    {{- include "symfony.labels" . | nindent 4 }}
  name: container-registry-cred
type: kubernetes.io/dockerconfigjson
