apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "symfony.labels" . | nindent 4 }}
  name: {{ include "symfony.fullname" . }}
spec:
  ports:
    -
      name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: http
  selector:
    {{- include "symfony.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
