{{- if and .Values.server.externalSecrets.enabled .Values.server.externalSecrets.awsProvider.enabled -}}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  labels:
    {{- include "immich.server.labels" . | nindent 4 }}
  name: {{ include "immich.server.fullname" . }}
spec:
  provider:
    aws:
      auth:
        secretRef:
          accessKeyIDSecretRef:
            key: access-key
            name: {{ include "immich.server.fullname" . }}-awssm-iam
          secretAccessKeySecretRef:
            key: secret-access-key
            name: {{ include "immich.server.fullname" . }}-awssm-iam
      region: {{ .Values.server.externalSecrets.awsProvider.region }}
      service: SecretsManager
{{- end -}}