{{- if and .Values.server.externalSecrets.enabled .Values.server.externalSecrets.awsProvider.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "immich.server.labels" . | nindent 4 }}
  name: {{ include "immich.server.fullname" . }}-awssm-iam
stringData:
  access-key: {{ .Values.server.externalSecrets.awsProvider.iam.accessKey | quote }}
  secret-access-key: {{ .Values.server.externalSecrets.awsProvider.iam.secretAccessKey | quote }}
type: Opaque
{{- end -}}