{{- if and .Values.server.externalSecrets.enabled .Values.server.externalSecrets.awsProvider.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  labels:
    {{- include "immich.server.labels" . | nindent 4 }}
  name: {{ include "immich.server.fullname" . }}
spec:
  data:
    {{- range .Values.server.externalSecrets.data }}
    - remoteRef:
        key: {{ .remoteRef.key }}
        {{- if .remoteRef.property }}
        property: {{ .remoteRef.property }}
        {{- end }}
        {{- if .remoteRef.version }}
        version: {{ .remoteRef.version }}
        {{- end }}
      secretKey: {{ .secretKey }}
    {{- end }}
  refreshInterval: {{ .Values.server.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: SecretStore
    name: {{ include "immich.server.fullname" . }}
  target:
    creationPolicy: Owner
    name: {{ include "immich.server.fullname" . }}-eso
{{- end -}}