{{- if or .Values.server.env.secret .Values.redis.password }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "immich.server.labels" . | nindent 4 }}
  name: {{ include "immich.server.fullname" . }}
stringData:
  {{- if .Values.redis.password }}
  REDIS_PASSWORD: {{ .Values.redis.password | quote }}
  {{- end }}
  {{- if not .Values.database.enabled }}
  {{- if not (hasKey .Values.server.env.secret "DB_PASSWORD") }}
  DB_PASSWORD: {{ .Values.database.password | quote }}
  {{- end }}
  {{- end }}
  {{- range $key, $val := .Values.server.env.secret }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
type: Opaque
{{- end -}}