{{- if and .Values.redis.enabled .Values.redis.serviceAccount.create -}}
apiVersion: v1
automountServiceAccountToken: {{ .Values.redis.serviceAccount.automount }}
kind: ServiceAccount
metadata:
  {{- with .Values.redis.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "immich.redis.labels" . | nindent 4 }}
  name: {{ include "immich.redis.serviceAccountName" . }}
{{- end }}