name: Package & Publish Helm Charts

# Grant write access so the bot can push to gh-pages
permissions:
  contents: write
  pages: write

on:
  push:
    branches:
      - main
    #paths:
    #  - 'charts/**'

jobs:
  publish:
    name: Lint · Render · Package · Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.17.3

      - name: Lint all charts
        run: |
          for dir in charts/*; do
            echo "⎯⎯ Linting $(basename $dir) ⎯⎯"
            helm lint "$dir"
          done

      - name: Install kube-linter
        run: |
          curl -sSL -o kube-linter-linux-amd64.tar.gz https://github.com/stackrox/kube-linter/releases/latest/download/kube-linter-linux-amd64.tar.gz
          file kube-linter-linux-amd64.tar.gz # This will tell you the actual file type
          tar -xzf kube-linter-linux-amd64.tar.gz
          sudo mv kube-linter /usr/local/bin/

      - name: Run kube-linter on all charts
        run: |
          for dir in charts/*; do
            chart=$(basename "$dir")
            echo "⎯⎯ kube-linter for $chart ⎯⎯"
            helm template "$dir" | kube-linter --config .kube-linter.yaml lint -
          done

      - name: Render templates
        run: |
          for dir in charts/*; do
            chart=$(basename "$dir")
            echo "⎯⎯ Rendering $chart ⎯⎯"
            # note: no --validate here!
            helm template "$chart" "$dir"
          done

      - name: Package charts
        run: |
          rm -rf .chart-packages
          mkdir .chart-packages
          for dir in charts/*; do
            chart=$(basename "$dir")
            echo "⎯⎯ Packaging $chart ⎯⎯"
            helm package "$dir" --destination .chart-packages
          done

      - name: Rebuild index
        run: |
          helm repo index .chart-packages \
            --url https://charts.reddevs.io

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .chart-packages
          publish_branch: gh-pages
