name: Package Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'

jobs:
  package-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Package Helm Charts
        run: |
          helm package charts/*

      - name: Update Index
        run: |
          helm repo index --url https://charts.reddevs.io/ .

      - name: Commit and Push
        env:
          PAT: ${{ secrets.PAT_FOR_ACTIONS }}
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add .
          git commit -m "Update Helm chart packages and index"
          git push https://${PAT}@github.com/${GITHUB_REPOSITORY}.git
