name: Package & Publish Helm Charts

# Grant write access so the bot can push to gh-pages
permissions:
  contents: write
  pages: write

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Lint · Render · Package · Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Lint all charts
        run: |
          for dir in charts/*; do
            echo "⎯⎯ Linting $(basename $dir) ⎯⎯"
            helm lint "$dir"
          done

      - name: Render templates
        run: |
          for dir in charts/*; do
            chart=$(basename "$dir")
            echo "⎯⎯ Rendering $chart ⎯⎯"
            # note: no --validate here!
            helm template "$chart" "$dir"
          done

      - name: Package charts
        run: |
          rm -rf .chart-packages
          mkdir .chart-packages
          for dir in charts/*; do
            chart=$(basename "$dir")
            echo "⎯⎯ Packaging $chart ⎯⎯"
            helm package "$dir" --destination .chart-packages
          done

      - name: Rebuild index
        run: |
          helm repo index .chart-packages \
            --url https://charts.reddevs.io

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .chart-packages
          publish_branch: gh-pages
