name: Package & Publish Helm Charts

# Grant write access so the bot can push to gh-pages
permissions:
  contents: write
  pages: write # Required for GitHub Pages deployments

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'

jobs:
  publish:
    name: Lint · Render · Package · Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.17.3 # Your specified Helm version

      - name: Lint all charts
        run: |
          helm lint charts/*

      - name: Install kube-linter
        run: |
          go install golang.stackrox.io/kube-linter/cmd/kube-linter@latest
          echo "Verifying kube-linter installation and version:"
          kube-linter version # This helps confirm it's installed and in PATH

      - name: Run kube-linter on all charts
        run: |
          for dir in charts/*; do
            chart=$(basename "$dir")
            values_file="$dir/linter-values.yaml"
            echo "⎯⎯ kube-linter for $chart ⎯⎯"
            if [ -f "$values_file" ]; then
              helm template "$dir" -f "$values_file" | kube-linter --config .kube-linter.yaml lint -
            else
              helm template "$dir" | kube-linter --config .kube-linter.yaml lint -
            fi
          done

      - name: Package charts
        run: |
          rm -rf .chart-packages
          mkdir .chart-packages
          for dir in charts/*; do
            chart=$(basename "$dir")
            echo "⎯⎯ Packaging $chart ⎯⎯"
            helm package "$dir" --destination .chart-packages
          done

      - name: Rebuild index
        run: |
          helm repo index .chart-packages \
            --url https://charts.reddevs.io # Ensure this URL is correct

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .chart-packages
          publish_branch: gh-pages
          cname: charts.reddevs.io
