{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.awsProvider.enabled .Values.externalSecrets.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "outline.fullname" . }}-aws-secret-store-iam
  labels:
    {{- include "outline.labels" . | nindent 4 }}
type: Opaque
data:
  access-key: {{ .Values.externalSecrets.awsProvider.iam.accessKey | b64enc }}
  secret-access-key: {{ .Values.externalSecrets.awsProvider.iam.secretAccessKey | b64enc }}
{{- end }}
