{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.awsProvider.enabled .Values.externalSecrets.data }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  labels:
    {{- include "outline.labels" . | nindent 4 }}
  name: {{ include "outline.fullname" . }}-aws-secret-store
spec:
  provider:
    aws:
      auth:
        secretRef:
          accessKeyID:
            key: access-key
            name: {{ include "outline.fullname" . }}-aws-secret-store-iam
          secretAccessKey:
            key: secret-access-key
            name: {{ include "outline.fullname" . }}-aws-secret-store-iam
      region: {{ .Values.externalSecrets.awsProvider.region }}
      service: SecretsManager
{{- end }}
