{{- if .Values.database.ssl.enabled }}
apiVersion: v1
data:
  database-ca.pem: {{ .Values.database.ssl.caCert | b64enc }}
kind: Secret
metadata:
  labels:
    {{- include "outline.labels" . | nindent 4 }}
  name: {{ include "outline.fullname" . }}-database-ca
type: Opaque
{{- end }}
