{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.awsProvider.enabled .Values.externalSecrets.data }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    {{- include "outline.labels" . | nindent 4 }}
  name: {{ include "outline.fullname" . }}-eso
spec:
  data:
  {{- range .Values.externalSecrets.data }}
    - remoteRef:
        key: {{ .remoteRef.key }}
        property: {{ .remoteRef.property }}
        {{- if .remoteRef.version }}
        version: {{ .remoteRef.version }}
        {{- end }}
      secretKey: {{ .secretKey }}
  {{- end }}
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: SecretStore
    name: {{ include "outline.fullname" . }}-aws-secret-store
  target:
    creationPolicy: Owner
    name: {{ include "outline.fullname" . }}-eso
{{- end }}
